### ISSUE TITLE
2015 consumed media

### ISSUE THREAD

**Issue by rick** [rick/life#7]
![](http://images6.fanpop.com/image/photos/33200000/Books-books-to-read-33242884-500-345.jpg)

**Comment by rick** [comment]
:book:
- [x] **Jan. 1** - [The Collected Works of Chogyam Trungpa, Vol. 1](http://www.amazon.com/Collected-Works-Chogyam-Trungpa-Meditation/dp/1590300254/) :star2: :star2: :star2: :star2:

Just finished this, after having it part-way for a few months. A great read, including the historical record **Born in Tibet**, other highlights include essays on bodhisattvas, etc.

**Comment by rick** [comment]
:cd:
- [x] **Jan. 2** - [Prince - ART OFFICIAL AGE](http://www.rdio.com/artist/Prince/album/ART_OFFICIAL_AGE/) :star2: :star2: :star2: :star2: ?

**Comment by rick** [comment]
:cd:
- [x] [Saint Etienne - Words and Music by Saint Etienne](http://www.rdio.com/artist/Saint_Etienne/album/Words_And_Music_By_Saint_Etienne/) - -- :star2: :star2: :star2:? 
- [x] [Al Green - Livin' For You](http://www.rdio.com/artist/Al_Green/album/Livin%27_For_You/) :star2: :star2: :star2:
- [x] [Steve Wonder - Fulfillingness' First Finale](http://www.rdio.com/artist/Stevie_Wonder/album/Fulfillingness%27_First_Finale/) :star2: :star2: :star2:

**Comment by rick** [comment]
:book:
- [x] [Maverick](http://www.amazon.com/Maverick-Success-Behind-Unusual-Workplace/dp/0446670553/) :star2: :star2: :star2: :star2:

Started reading this early in my past job stint (i.e., probably late 2012) and never finished it.  Finally buckled down and read the 2nd half. It's a pretty fascinating book. Lots of crazy and amazing things they've done to a company that came from a hardcore pyramid-style hierarchy in an industrial/factory setting. Lots of it might or might not be portable, but the idea of letting your people dictate how to succeed, no matter how radical the ideas, is portable to anywhere.

Saddened to see a company doing more radical and inspiring things than Semco having become a place which probably can't even aspire to being half as radical as Semco.  :crying_cat_face:  _anicca_, I suppose.

**Comment by rick** [comment]
![](http://cdn2.thelineofbestfit.com/media/2012/12/nils-frahm-screws.jpg)

:cd:
- [x] [Nils Frahm - Screws](http://www.rdio.com/artist/Nils_Frahm/album/Screws/) :star2: :star2: :star2: :star2:?

Very chill, would be good for listening to during programming / reading, etc.
- [x] [Nils Frahm - The Bells](http://www.rdio.com/artist/Nils_Frahm/album/The_Bells_1/) :star2: :star2: :star2:

Also good, but a little more scattered than "Screws".

**Comment by rick** [comment]
:book: 
- [x] [the life-changing magic of tidying up](http://www.amazon.com/Life-Changing-Magic-Tidying-Decluttering-Organizing/dp/1607747308/) :star2: :star2: :star2: :star2: :star2:

Actually, this might be a :100:% literally correct title. Quite possibly life changing.  Highly recommended reading.

**Comment by rick** [comment]
:movie_camera: 
- [x] [Fury](http://en.wikipedia.org/wiki/Fury_%282014_film%29)

Bitchin'.

:movie_camera:
- [x] [World War Z](http://en.wikipedia.org/wiki/World_War_Z)

Surprisingly good zombie movie.  Kind of a Brad Pitt "I Am Legend" with a different spin.

**Comment by rick** [comment]
:movie_camera: 
- [x] [The Hobbit: The Battle of the Five Armies](http://en.wikipedia.org/wiki/The_Hobbit:_The_Battle_of_the_Five_Armies)

The final conclusion to the huge departure from the book that somehow became a trilogy. I enjoyed it, but had to forget the content of the book.

**Comment by rick** [comment]
:movie_camera: 
- [x] [The World's End](http://en.wikipedia.org/wiki/The_World%27s_End_%28film%29)

Somehow had missed this when it came out. A pretty good zombie-style movie (alien invaders); cast from Shawn of the Dead, etc.

**Comment by norbert** [comment]
@rick their previous two movies were significantly better but it was entertaining nonetheless.

Personally I use @mislav's [Movi.im](http://movi.im/) for tracking movies. I even built a recommender system for it but that's temporarily down.

**Comment by rick** [comment]
:computer: :satellite: 
- [x] [Invisibilia (NPR)](http://www.npr.org/programs/invisibilia/) - episodes 1 & 2; h/t @vinbarnes

**Comment by vinbarnes** [comment]
@rick really happy to have come across Invisibilia

**Comment by rick** [comment]
:computer: :satellite:
- [x] [Buddhist Geeks #002 - Alan Wallace on Achieving Shamatha](http://www.buddhistgeeks.com/2007/01/bg-002-alan-wallace-on-achieving-shamatha/) - a good listen about the practice of Shamatha, stages of shamatha concentration, etc.
- [x] [Buddhist Geeks #006 - Daniel Ingram, "You Can Do It!"](http://www.buddhistgeeks.com/2007/02/bg-006-you-can-do-it/) - a good (but advanced) interview with the author of [Mastering the Core Teachings of the Buddha](http://integrateddaniel.info/book/), talking somewhat about "maps" and the realizable possibility of enlightenment, etc.

**Comment by rick** [comment]
@vinbarnes -- yeah, that's a good find.  Mos' respect.

**Comment by rick** [comment]
:computer: :satellite:
- [x] [Buddhist Geeks #009](http://www.buddhistgeeks.com/2007/03/bg-009-enlightened-teachers/) and [Buddhist Geeks #011](http://www.buddhistgeeks.com/2007/03/bg-011-models-of-enlightenment/) - parts 2 & 3 from a discussion with Daniel Ingram (see above); :+1:

**Comment by rick** [comment]
:movie_camera: 
- [x] :lemon: :hankey: [Star Trev V: The Final Frontier](http://en.wikipedia.org/wiki/Star_Trek_V:_The_Final_Frontier) - pretty sure I never saw this. I think I remember when this came out, thinking about going to see it, and someone told me "don't bother, it sucked".  They were right.  Wow, is this bad.

**Comment by rick** [comment]
:movie_camera: 
- [x] [The Chronicles of Narnia: The Voyage of the Dawn Treader](http://en.wikipedia.org/wiki/The_Chronicles_of_Narnia:_The_Voyage_of_the_Dawn_Treader) - I had read all these books a few dozen times as a kid; hadn't seen this particular movie adaptation, so figured I'd try it.  It's fine; probably better for kids, especially if you want to load them up with latent Christian symbolism.  :shrug:

**Comment by rick** [comment]
:movie_camera: 
- [x] [Predestination](http://en.wikipedia.org/wiki/Predestination_%28film%29) - pretty cool time travel film in the general vein of Primer or Looper. (h/t @vinbarnes) I'm of the opinion that the big explosion in NYC was averted (i.e., it's not a loop in time but an iterating zigzag across evolving timelines), similar to the shenanigans being played by [Hiro Nakamura in "Heroes"](http://en.wikipedia.org/wiki/Hiro_Nakamura#Time_alterations) (that page doesn't include the loop of 47 time-travel trips to ultimately get a butt xeroxed...).

:book:
- [x] [The Mystery Method](http://www.amazon.com/The-Mystery-Method-Beautiful-Women/dp/1400154111) - don't hate me because I'm beautiful. Bumped into this online while looking for interesting audiobooks and just sat down and read it. I'd heard of this and various other similar "player" guides. There are parts that are somewhat manipulative, but mostly it's an interesting take on practical applied psychology. Whatevs.

**Comment by rick** [comment]
:movie_camera: 
- [x] [The Raven](http://en.wikipedia.org/wiki/The_Raven_%282012_film%29) -- I think this review puts it best: "Thinly scripted, unevenly acted, and overall preposterous, The Raven disgraces the legacy of Edgar Allen [sic] Poe with a rote murder mystery that's more silly than scary."
- [x] [The Score](http://en.wikipedia.org/wiki/The_Score_%282001_film%29) - decent; worth pulling up on netflix

Both of these were watched at the family manse in Kentucky right before I went on a meditation retreat.  Just now writing them down.

**Comment by rick** [comment]
:cd: :musical_note: 
- [x] [Panda Bear - Panda Bear Meets the Grim Reaper](http://en.wikipedia.org/wiki/Panda_Bear_Meets_the_Grim_Reaper) - definitely like it, not sure how to summarize it; worth a spin
- [x] [D'Angelo and The Vanguard - Black Messiah](http://en.wikipedia.org/wiki/Black_Messiah_%28album%29) - pretty solid soulful cuts, with hints of Prince and Outkast. 
- [x] [Title Fight: Hyperview](http://en.wikipedia.org/wiki/Hyperview) - definitely sound punk-turned-shoe-gazing; dig it

**Comment by rick** [comment]
- [x] :musical_note: [Bombay the Hard Way: Guns, Cars, and Sitars](http://en.wikipedia.org/wiki/Bombay_the_Hard_Way:_Guns,_Cars_and_Sitars) - probably not everyone's cup of chai, but I love shit like this.  Some of the titles are incredible, but the songs I really dig are the ones with the movie audio tracks and bad-ass grooves. "My Guru", "Theme from Don" (almost makes me want to legally change my name; the Beastie Boys must've never heard this groove or they would've sampled it), and "Inspector Jay from Delhi" are all ridiculous.

**Comment by rick** [comment]
- [x] :movie_camera: [X-Men: Days of Future Past](http://en.wikipedia.org/wiki/X-Men:_Days_of_Future_Past) - great action movie; probably requires having seen the earlier films (or knowing a lot about the franchise) to get all the references

**Comment by rick** [comment]
- [x] :movie_camera: [What We Do in the Shadows](http://en.wikipedia.org/wiki/What_We_Do_in_the_Shadows) - lol. Thoroughly enjoyed this.
- [x] :cd: [Monsters of Folk - Monsters of Folk](http://en.wikipedia.org/wiki/Monsters_of_Folk_%28album%29) - hadn't caught this back in 2009 when it came out; worth a listen

**Comment by rick** [comment]
- [x] :guitar: (seen live): [The Ascent of Everest](https://www.facebook.com/theascentofeverest) - really tight heavy rock band with a cello front. Recommended.

**Comment by rick** [comment]
- [x] :cd: :satellite: http://somethingelsereviews.com/2015/02/19/booker-t-and-the-mgs-creedence-clearwater-revival/ (h/t @rimboy)

**Comment by rick** [comment]
- [x] :cd: [Johnny Jenkins - Ton Ton Macoute!](http://en.wikipedia.org/wiki/Ton-Ton_Macoute!) ([rdio](https://www.rdio.com/artist/Johnny_Jenkins/album/Ton-Ton_Macoute!/)) - legit.  (h/t @vinbarnes)

**Comment by rick** [comment]
- [x] :cd: [Lord Huron - Lonesome Dreams](http://www.rdio.com/artist/Lord_Huron/album/Lonesome_Dreams/) - pretty chill; another "I missed this when it came out" album; h/t/ A.H.

**Comment by rick** [comment]
- [x] :cd: [Mogwai - Music Industry 3. Fitness Industry 1.](http://pitchfork.com/news/56955-mogwai-announce-music-industry-3-fitness-industry-1-ep-share-teenage-exorcists/) - [(rdio)](http://www.rdio.com/artist/Mogwai/album/Music_Industry_3._Fitness_Industry_1./) - solid, nice little EP.

**Comment by rick** [comment]
- [x] :satellite: :video_camera: [frank sinatra - the girl from ipanema](https://www.youtube.com/watch?v=NldPFVKYmiw) h/t @wilkes iirc

**Comment by rick** [comment]
- [x] :book: [Wilco - Learning How To Die](http://www.amazon.com/Wilco-Learning-How-Greg-Kot/dp/0767915585) -- borrowed from the @rimboy. Definitely a good read if you're into Uncle Tupelo / Wilco (only the tiniest bit in here about Son Volt), goes up through Yankee Hotel Foxtrot, with a tiny bit about the creation of A Ghost is Born.  A good companion to [I am trying to break your heart](http://www.amazon.com/Wilco-Learning-How-Greg-Kot/dp/0767915585) :movie_camera:, which covers the Yankee Hotel Foxtrot era pretty well.

**Comment by rick** [comment]
- [x] :cd: [Color of Clouds - Nine of Arrows](http://www.rdio.com/artist/Color_of_Clouds/album/Nine_of_Arrows/) - meh.

**Comment by rick** [comment]
- [x] :book: [Haruki Murakami - the Strange Library](http://www.amazon.com/Strange-Library-Haruki-Murakami/dp/0385354304/ref=tmm_pap_swatch_0?_encoding=UTF8&sr=8-7&qid=1431965571)

The "paperback" edition is pretty awesome, interesting fold-out, lots of art, etc.  I started reading this (it's like a 15 minute read) and thought "maybe this would be cool as a kid's story", ... "well, maybe young adult" ... "nope."

Really liked it. :-)

**Comment by rick** [comment]
- [ ] :tv: [Daredevel](https://en.wikipedia.org/wiki/Daredevil_%28TV_series%29) -- holy shit, so good
- [ ] :book: [Seveneves](http://www.amazon.com/Seveneves-A-Novel-Neal-Stephenson/dp/1501220233) by Neal Stephenson -- solid, engaging read; still weak on his endings, but he's such a good writer otherwise
